export {
    IconUser,
    IconBell,
    IconBrandWhatsapp,
    IconBrandX,
    IconBrandFacebook,
    IconBrandInstagram,
    IconBrandTiktok,
    IconMenu2,
    IconX,
    IconArrowUpRight,
    IconStar,
    IconArrowRight,
    IconMail,
    IconLock,
    IconEye,
    IconEyeOff,
    IconBrandYoutube,
} from '@tabler/icons-react';